/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.GUI.abm;

import com.mycompany.GUI.Styles;
import com.mycompany.proyectofinal.Controladora;
import com.mycompany.proyectofinal.Usuario;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import com.mycompany.GUI.components.Btn;
import com.mycompany.proyectofinal.Producto;
import com.mycompany.proyectofinal.Servicio;
import com.mycompany.proyectofinal.ServicioProducto;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author duart
 */
public class AltaServicios extends JDialog {

    Controladora control = new Controladora();
    private Runnable onSave;
    Usuario empleadoSelec;
    private JTable tablaProductos;
    private DefaultTableModel modeloProductos;

    
  
    public AltaServicios(Frame parent, boolean modal, Runnable onSave) {
        super(parent, modal);
        this.onSave = onSave;
        
        initComponents();
        
        

        
        obtenerUsuarios(); //carga cbo
        //obtenerProductos();
        inicializarTablaProductos();
        cargarProductos();
        
        
        Btn btnAlta = Btn.primary("Guardar");
        btnAlta.setPreferredSize(Styles.btnSizeSm);
        btnPanel.add(btnAlta);
        
        Btn btnLimpiar = Btn.secondary("Limpiar");
        btnLimpiar.setPreferredSize(Styles.btnSizeSm);
        btnPanel.add(btnLimpiar);
        
        Btn btnCerrar = Btn.secondary("Cerrar");
        btnCerrar.setPreferredSize(Styles.btnSizeSm);
        btnPanel.add(btnCerrar);
        
        
        jPanel2.setBackground(Styles.bgLight);
        jPanel3.setBackground(Styles.bgLight);
        btnPanel.setBackground(Styles.bgLight);

        
        btnLimpiar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    txtNombre.setText("");
                    txtPrecio.setText("");
                    cboEmpleados.setSelectedIndex(-1);
                    //cboProductos.setSelectedIndex(-1);
                }
        });
        
        btnCerrar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dispose();
                }
        });
        
        btnAlta.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String nombre = txtNombre.getText();
                    String precio = txtPrecio.getText();
                    
                    //Guardar user seleccionado
                    String empleado = (String) cboEmpleados.getSelectedItem();
                    empleadoSelec = guardarEmpleado(empleado);
                    
                    //String nombreProducto = (String) cboProductos.getSelectedItem();
                    //Producto productoSeleccionado = guardarProducto(nombreProducto);

                    
                    if (validarCampos() && validarProductos()) {

                        guardarServicio();   // 🔥 CALL IT

                        JOptionPane.showMessageDialog(
                            null,
                            "Servicio guardado correctamente.",
                            "Servicio guardado.",
                            JOptionPane.INFORMATION_MESSAGE
                        );

                        if (onSave != null) {
                            onSave.run();
                        }

                        dispose();
                    }

                }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCargaEmp = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboEmpleados = new javax.swing.JComboBox<>();
        scrollProd = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));

        lblCargaEmp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCargaEmp.setText("Carga de Servicios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(lblCargaEmp)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(lblCargaEmp)
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        btnPanel.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.add(btnPanel, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jLabel1.setText("Nombre*");

        jLabel2.setText("Precio*");

        txtPrecio.setBackground(new java.awt.Color(242, 242, 242));
        txtPrecio.setForeground(new java.awt.Color(102, 102, 102));
        txtPrecio.setText("10000");
        txtPrecio.setBorder(null);
        txtPrecio.setPreferredSize(new java.awt.Dimension(73, 30));

        txtNombre.setBackground(new java.awt.Color(242, 242, 242));
        txtNombre.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre.setText("Servicio");
        txtNombre.setBorder(null);
        txtNombre.setPreferredSize(new java.awt.Dimension(73, 30));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Empleado");

        jLabel7.setText("Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollProd, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(scrollProd, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void inicializarTablaProductos() {

    modeloProductos = new DefaultTableModel(
        new Object[]{"Seleccionar", "Producto", "Cantidad"}, 0
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            switch (columnIndex) {
                case 0: return Boolean.class; // checkbox
                case 2: return Integer.class; // cantidad
                default: return String.class;
            }
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return column == 0 || column == 2; // only checkbox + cantidad editable
        }
    };

    tablaProductos = new JTable(modeloProductos);
    tablaProductos.setRowHeight(25);

    scrollProd.setViewportView(tablaProductos);
}

    private boolean validarCampos() {
        if (cboEmpleados.getSelectedItem()== null || 
            txtNombre.getText().isEmpty() || 
            txtPrecio.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return false; // Indicate validation failure
        }
        return true; // Indicate validation success
    }
    
    //cargar servicios a cbo
    public void obtenerUsuarios(){
        List<Usuario> usuarios = control.traerUsuarios();
        for (Usuario usu : usuarios) {
            String apellido = usu.getApellido();
            String nombre = usu.getNombre();
            String nombreComp;
            nombreComp = nombre + " " + apellido;
            cboEmpleados.addItem(nombreComp);  
        }
    }
    //encontrar servicio por nombre y guardar
    public Usuario guardarEmpleado(String emp){
        List<Usuario> usuarios = control.traerUsuarios();
        Usuario usuarioSeleccionado = null;

        for (Usuario usu : usuarios) {
            String nombreComp = usu.getNombre() + " " + usu.getApellido();
            
                if (nombreComp.equals(emp)) {
                    usuarioSeleccionado = usu;
                    break;
                }
        }

        
        if (usuarioSeleccionado != null) {
            return usuarioSeleccionado;
        } else {
            return null;
        }
    }
    
    
    
    private void cargarProductos() {

    modeloProductos.setRowCount(0);

    List<Producto> lista = control.traerProductos();

    for (Producto p : lista) {
        modeloProductos.addRow(new Object[]{
            false,
            p,      // 🔥 store entire object
            0
        });

    }
}
    
   private boolean validarProductos() {

    if (tablaProductos.isEditing()) {
        tablaProductos.getCellEditor().stopCellEditing();
    }

    for (int i = 0; i < modeloProductos.getRowCount(); i++) {

        Boolean seleccionado = (Boolean) modeloProductos.getValueAt(i, 0);
        Object cantidadObj = modeloProductos.getValueAt(i, 2);

        double cantidad = 0;

        if (cantidadObj instanceof Number) {
            cantidad = ((Number) cantidadObj).doubleValue();
        }

        if (seleccionado != null && seleccionado) {

            if (cantidad <= 0) {

                JOptionPane.showMessageDialog(
                    this,
                    "Si selecciona un producto, la cantidad debe ser mayor a 0.",
                    "Cantidad inválida",
                    JOptionPane.WARNING_MESSAGE
                );

                return false;
            }
        }
    }

    return true;
}


    
    private void guardarServicio() {

    if (tablaProductos.isEditing()) {
        tablaProductos.getCellEditor().stopCellEditing();
    }

    Servicio servicio = new Servicio();
    servicio.setNombre(txtNombre.getText());
    servicio.setPrecio(txtPrecio.getText());
    servicio.setEmpleado(empleadoSelec);

    for (int i = 0; i < modeloProductos.getRowCount(); i++) {

        Boolean seleccionado = (Boolean) modeloProductos.getValueAt(i, 0);
        Producto producto = (Producto) modeloProductos.getValueAt(i, 1);
        Integer cantidad = (Integer) modeloProductos.getValueAt(i, 2);

        if (seleccionado != null && seleccionado && cantidad != null && cantidad > 0) {

            ServicioProducto sp = new ServicioProducto();
            sp.setProducto(producto);
            sp.setCantidadUsada(cantidad);

            servicio.addProducto(sp);
        }
    }

    control.guardarServicio(servicio);
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPanel;
    private javax.swing.JComboBox<String> cboEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCargaEmp;
    private javax.swing.JScrollPane scrollProd;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
